PaeP3nguin/honkai-guide

package-lock.json, src/data/valk_multipliers.ts
Added TP, SN, AE, VK, and grammar
=> Added Valk Multipliers including TP

src/data/stig_multipliers.ts, src/data/weapon_multipliers.ts
- Weapons
- DPS
- Abyss Flower
- Lance of Longinus
- Support
- Crusher Bunny 19C
- Stigmata
- DPS
- Avogadro
- Dickens
- Attila
- Fu Hua Pride
- Children/Columbus
- Support
- Avogadro
- Turgenev
=> Adding a handful of stigmata and weapon data

src/data/stig_multipliers.ts, src/data/weapon_multipliers.ts
Added the new signature equipment; I'm actually unsure on the M stig multiplier category but the wording appears to be consistent with the other similar stigs
=> HoFs equipment

src/data/stig_multipliers.ts, src/data/weapon_multipliers.ts
New Elysia stigs and bows, also AF PRI
Intentional departure from other PRI descriptions because I think "Abyss Flower Liminal Spiral" is just a bit too much
=> V5.1 equipment

src/data/stig_multipliers.ts, src/data/weapon_multipliers.ts
Paganini and Miracle Kissy Pillow added; I sure hope it was worth spending all my 5.2 crystals on these...
=> Carole equipment

src/pages/Search.vue
Request by Nyanbre#1578 in the official Honkai discord to add the following tags for PE
=> Palatinus Equinox chinese search terms

src/data/stig_multipliers.ts, src/data/weapon_multipliers.ts
Oh yeah, the other valk this patch xd
=> Spina Astera gear

src/data/stig_multipliers.ts, src/data/weapon_multipliers.ts
This damn gear and cat robbed me of my saved up crystals
=> Felis gear

src/pages/Search.vue
Search term requested by 브라우저잇올#3644
=> Added felis search tag

src/data/stig_multipliers.ts, src/data/weapon_multipliers.ts
=> Eden equipment

src/data/stig_multipliers.ts, src/data/weapon_multipliers.ts
=> Aponia equipment

src/pages/Search.vue
Added a new toggle box to search bilibili through google instead of Bilibili directly.
Added a toggle to remove the bilibili site: criteria to search the whole internet for the same CN keywords.
While toggled, the search generator will bypass the existing one, and create a search string compatible with google Boolean searches. by default it will add the bilibili address to the search which limits it to bilibili.
Feel free to clean up anything. This is my first time really doing something on vue, so I just kinda guessed on how to add the buttons. <3
Suggestions/Future Additons
Not Added - Date Selectors to handle google's "before:" and "after:" tags, which could be good for limiting searches to new OR old runs.
Not Added - more equipment searches like for LWH or Ana etc. Seemed like a lot …
=> + Toggleable Google Search

src/data/stig_multipliers.ts, src/data/weapon_multipliers.ts
Pretty sure these are the correct effects after asking around on the discord and cross-checking the translations.
What should we do about bleed damage buffs by the way? Same thing we did with shield damage?
=> Griseo gear

src/data/weapon_multipliers.ts
A bit late, but here's the new dkey
=> Seven thunders

src/data/weapon_multipliers.ts
=> Elysian astra fix

src/data/stig_multipliers.ts, src/data/weapon_multipliers.ts
Added VV late since v5.9 was totally a skip patch
=> Vill V equips

src/data/stig_multipliers.ts, src/data/weapon_multipliers.ts
=> Hoh equips

src/pages/Search.vue
Not sure if there are other abbreviations for Sus, but hopefully these will do for now
Oh also, apparently a lot of videos abbreviate HoH with the character for human; makes sense
=> Sus search

src/data/stig_multipliers.ts, src/data/weapon_multipliers.ts
=> Sus equips

src/data/stig_multipliers.ts, src/data/weapon_multipliers.ts
New Divine Key that is named the same as the other dkey but the other one sucks so much it doesn't deserve the acronym. Also the new G4 Ice stigs
=> Soe willows

src/pages/Scores.vue, src/pages/Search.vue, src/util/score_util.ts
Refactor score naming convention (minor)
Scores look right to me so far.
Hopefully didnt miss anything
=> Add SSS Base score, remove SS Up

src/pages/Search.vue
=> Adding Kalpas boss search terms

src/pages/Search.vue
=> No ELFs search term

src/pages/Search.vue
=> Ai search terms

src/pages/Search.vue
=> HoTr search terms

src/data/weapon_multipliers.ts
=> Adding Echo PRI

src/data/stig_multipliers.ts, src/data/weapon_multipliers.ts
Mmm, we might need to add bleed damage increase/taken independent multipliers; waiting for the motivated people to figure out exactly what goes where--I'll open a separate issue tracker for it in a bit.
For now I'm just gonna shove bleed specific DMG multipliers into the phys buckets
=> Valkyrie Quicksand gear

src/pages/Search.vue
Preliminary search terms to use for the new blob boss and Susan refs
Thanks to fragile and Joshie
=> Slime boss and VQ search

src/pages/Search.vue
- added localized name
- added secondary CN name
- added beta test modifier
=> Updated 6.7 boss name, added new beta test modifier

src/pages/Search.vue
Added 6.8 beta boss and Herrscher of Rebirth search terms
=> Added 6.8 beta boss and Herrscher of Rebirth

src/pages/Search.vue
=> Added 6.9 valkyrie Miracle Magical Girl (Sirin)

src/pages/Search.vue
This boss is from a long time ago, but the keyword for it was missing :P
=> Added missing boss Herrscher of Corruption Elysia

src/pages/Search.vue
English name for the new boss probably coming in a few more weeks!
=> V7.1 updates

src/pages/Search.vue
7.1 GLB beta is out; added EN name for boss
=> Added new things from v7.1 beta

src/pages/Search.vue
This is pretty late cause I was away on vacation!  Hopefully you have time to get this in for us soon, Fu Hua will be playable on Thursday.
=> Added 7.2 new Fu Hua

src/pages/Search.vue
=> Fixed mistake in alien guard name
